spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lorely
    username: postgres
    password: '!Nysu1726'

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.lorely: DEBUG
    org.springframework.security: DEBUG
